spring.application.name=inquiry-service

server.port=${PORT:8083}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.main.lazy-initialization=true

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

spring.jpa.open-in-view=false